name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Read go version
        id: go-version
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"
      -
        name: Set up Go
        uses: actions/setup-go@v2
        env:
          GOPROXY: https://proxy.golang.org/
        with:
          # TODO: Replace with go-version-from-file when it is supported
          # https://github.com/actions/setup-go/pull/62
          go-version: ${{ steps.go-version.outputs.content }}
      - # since release builds specify the preloadschema tag, we must run the generator
        name: Generate provider schemas
        run: go generate ./internal/schemas
      -
        name: Snapshot build (cross-platform)
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --skip-post-hooks

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Read go version
        id: go-version
        shell: bash
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          # TODO: Replace with go-version-from-file when it is supported
          # https://github.com/actions/setup-go/pull/62
          go-version: ${{ steps.go-version.outputs.content }}
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Go mod download
        run: go mod download -x
      -
        name: Go mod verify
        run: go mod verify
      -
        name: Run go fmt
        run: make fmt
      -
        name: Run tests
        run: go test -cover -covermode=atomic -timeout=5m -race ./...
