name: release

on:
  push

permissions:
  contents: write # for uploading release artifacts
  issues: write # for closing milestone via goreleaser
  packages: read # for downloading signore docker image

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Read go version
        id: go-version
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          # TODO: Replace with go-version-from-file when it is supported
          # https://github.com/actions/setup-go/pull/62
          go-version: ${{ steps.go-version.outputs.content }}
      -
        name: Generate provider schemas
        run: go generate ./internal/schemas
      -
        name: Install hc-codesign
        run: |
          docker login docker.pkg.github.com -u docker -p '${{ secrets.CODESIGN_GITHUB_TOKEN }}' && \
          docker pull docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION && \
          echo "::set-output name=image::docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION"
        id: codesign
        env:
          VERSION: v0
      -
        name: Install signore
        uses: hashicorp/setup-signore-package@v1
      -
        name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          CODESIGN_IMAGE: ${{ steps.codesign.outputs.image }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
          SIGNORE_CLIENT_ID: ${{ secrets.SIGNORE_CLIENT_ID }}
          SIGNORE_CLIENT_SECRET: ${{ secrets.SIGNORE_CLIENT_SECRET }}
          SIGNORE_SIGNER: ${{ secrets.SIGNORE_SIGNER }}
      - 
        name: copy artifacts
        run: |
          mkdir dist/all-artifacts
          cp dist/terraform-ls_0.26.0-beta1* dist/all-artifacts
          mkdir dist/zips
          cp dist/terraform-ls_0.26.0-beta1*.zip dist/zips/
      -
        name: Publish released artifacts
        uses: hashicorp/actions-hc-releases@initial-dev
        with:
          version: "v0.26.0-beta1-SNAPSHOT-2"
          private-tools-token: "${{ secrets.CODESIGN_GITHUB_TOKEN }}"
          product-name: "terraform-ls"
          hc_releases_host: "${{ secrets.HC_RELEASES_HOST }}"
          hc_releases_key: "${{ secrets.HC_RELEASES_KEY }}"
